import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProfileProvider from "./core/providers/ProfileProvider";
import InvestorIDProvider from "./core/providers/InvestorIDProvider";
import Sidebar from "./components/dashboard/sidebar";
import dynamic from "next/dynamic";
import Header from "./components/dashboard/header";

const SideBar = dynamic(
  () => import("./components/dashboard/sidebar"),
  {
    loading: () => <p>Loading...</p>,
  }
);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex w-full"> 
        <ProfileProvider>
          <InvestorIDProvider>
            <Sidebar/>
            {children}
          </InvestorIDProvider>
        </ProfileProvider>
      </body>
    </html>
  );
}
